### ISSUE TITLE
Non-native arithmetic - Milestone 3

### ISSUE THREAD

**Issue by lazovicff** [eigen-trust/eigen-trust#63]
Chips for non-native field arithmetic - wrong field operations using custom gates - https://hackmd.io/@arielg/B13JoihA8
- [x] Build a native version of Integer for non-native field arithmetic operations used in proof aggregation.
- [x] Build a native version of Elliptic Curve arithmetic operations for proof aggregation.
- [x] Build an Integer chip using Halo2.
- [x] Build an Elliptic Curve chip using Halo2.

Bonus:
Research on proof aggregation:
https://github.com/scroll-tech/halo2-snark-aggregator
https://github.com/privacy-scaling-explorations/plonk-verifier
